### ISSUE TITLE
Add event by long touch in day or week view isn't working anymore on xenial

### ISSUE THREAD

**Issue by hummlbach** [ubports/calendar-app#128]
https://forums.ubports.com/topic/1747/add-event-in-calendar-in-day-view-or-week-view

**Comment by hummlbach** [comment]
The following can be found in the log:

```
file:///opt/click.ubuntu.com/com.ubuntu.calendar/0.7.4/qml/TimeLineBase.qml:46: TypeError: Property 'defaultCollection' of object EventListModel_QMLTYPE_39(0xa8c628, "timeLineBaseEventListModel:DayComponent-0") is not a function
```

Creating new invent from month or year view doesn't look up the default calendar (#64) and is still working, so i guess this has the same root cause as #129.

**Comment by tjrhodes** [comment]
device: Fairphone 2
channel: RC 2018-W48
issue remains, can only add an event with a long press in the month view.

**Comment by UniversalSuperBox** [comment]
Sorry @hummlbach, I thought the fix was released.

**Comment by hummlbach** [comment]
No problem. Waiting for the review/approval of #130 and #134. Afterwards i'll do the release. I closed, it since it was merged to trunk. Should I better close the bug when the release is through. But also it does not make much sense to add pass it over to QA after it has been released in the openstore... I posted a beta click containing all the fixes in the QA group some days ago, with that it should work indeed.

**Comment by Flohack74** [comment]
Normally QA needs to know when to approve and this is when the issue is being closed = fix committed. For the core apps though, the idea was that they get built by CI for the devel image only, and not appear in the Openstore, so bypasssing a public release problem. Please discuss this with @bhdouglass and the App team. The click builder is there, but should not push devel or rc builds to the Openstore, of course.

We do not want to install core Apps as deb packages whenever possible. So only those with special privileges will be built as deb and added to the image directly. Thats the final goal ;)

**Comment by bhdouglass** [comment]
Currently the way I'm setting up the CI for the core apps moving to GitLab is that they only push to the OpenStore when there is a new git tag. So that way it'll get built and have clicks available for every commit, but only publish them on tags. We could set it up so every commit pushes the click to be put into devel/rc and keep the tags for actual releases (this would be a good time to have beta support in the OpenStore).
